#
#  Author: Hari Sekhon
#  Date: 2022-03-30 13:01:09 +0100 (Wed, 30 Mar 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: AWS CodeCommit Mirror

on:
  workflow_call:
    inputs:
      organization:
        description: The GitHub Organization that owns the repos (defaults to the user of the given GITHUB_TOKEN)
        type: string
        required: false
      repos:
        description: List of repos to mirror, space separated (otherwise iterates and mirrors all repos belonging to the GITHUB_ORGANIZATION or GITHUB_USER)
        type: string
        required: false
        default: ""
      clear_cache:
        type: string
        required: false
        default: false
      force_mirror:
        type: string
        required: false
        default: false
      debug:
        type: string
        required: false
        default: false
    secrets:
      GH_TOKEN:
        description: GitHub Token with permissions 'repo' and 'read:org' to list GitHub repos
        required: true
      AWS_ACCESS_KEY_ID:
        description: AWS access key ID with permissions to create new repos to mirror to
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: AWS secret access key with permissions to create new repos to mirror to
        required: true
      # the reason this is a secret and not an input is because you can set this secret Organization wide on GitHub and just inherit it
      AWS_DEFAULT_REGION:
        description: AWS region where the repos should exist
        required: true
      AWS_GIT_USER:
        description: AWS Git username (optional), falls back to using git-remote-codecommit python module to use IAM integration otherwise
        required: false
      AWS_GIT_PASSWORD:
        description: AWS Git password (optional), falls back to using git-remote-codecommit python module to use IAM integration otherwise
        required: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  REPOS: ${{ inputs.repos }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_ORGANIZATION: ${{ inputs.organization }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_GIT_USER: ${{ secrets.AWS_GIT_USER }}
  AWS_GIT_PASSWORD: ${{ secrets.AWS_GIT_PASSWORD }}
  DEBIAN_FRONTEND: noninteractive
  CLEAR_CACHE: ${{ inputs.clear_cache == 'true' || github.event.inputs.clear_cache == 'true' }}
  FORCE_MIRROR: ${{ inputs.force_mirror == 'true' || github.event.inputs.force_mirror == 'true' }}
  DEBUG: ${{ inputs.debug == true || github.event.inputs.debug == 'true' || '' }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false  # killing this part way through may leave inconsistencies

jobs:
  codecommit_mirror:
    name: Mirror Repos to AWS CodeCommit
    # the schedule event doesn't have github.event.repository.* to compare branches so needs to just check for event_name instead
    #if: |
    #  github.event.repository.fork == false &&
    #  (
    #    github.event_name == 'schedule' ||
    #    ( github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch )
    #  )
    runs-on: ubuntu-latest
    container: harisekhon/bash-tools
    steps:
      - name: Environment
        run: env | sort

      # not needed since everything is done via the GitHub and GitLab APIs and iterated checkouts
      #- uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: /tmp/github_mirror_to_aws_codecommit
          key: github-mirror-to-aws-codecommit
          restore-keys: |
            github-mirror-to-aws-codecommit

      - name: Mirror Repos
        run: github_mirror_repos_to_aws_codecommit.sh $REPOS
