#
#  Author: Hari Sekhon
#  Date: 2022-01-24 16:49:38 +0000 (Mon, 24 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 D o c k e r   B u i l d   ->   A W S   E C R
# ============================================================================ #

# Docker Build, Tag & Push to AWS ECR

---
name: Docker Build -> AWS ECR

on:
  workflow_call:
    inputs:
      repo:
        description: The ECR repository, without the 'xxx.dkr.ecr.<region>.amazonaws.com' prefix
        type: string
        required: true
      max-cache:
        description: Use external cache image to capture multi-stage build cache, uses GHCR as a max cache external registry (ECR doesn't support this at time of writing)
        type: boolean
        default: false
        required: false
      build-cache:
        description: The build cache tag to use
        type: string
        default: buildcache
      dockerfile-repo:
        description: A separate repo where the Dockerfile for the build can be found. Will be checked out first to a directory of the same name
        type: string
        required: false
      dockerfile-ref:
        description: The branch from dockerfile-repo to checkout (defaults to the default branch if not specified)
        type: string
        required: false
      context:
        description: the Docker context directory for the docker build
        type: string
        required: false
        default: .
      file:
        description: the Dockerfile to build from. Defaults to Dockerfile inside the context. If specifying context, needs to include the context path prefix
        type: string
        #default: Dockerfile  # breaks auto-pathing when specifying context, you'd have to remember to set file to $context/Dockerfile yourself, better to omit this
      debug:
        type: string
        required: false
        default: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  AWS_ECR_REPO: ${{ inputs.repo }}
  BUILDCACHE: ${{ inputs.build-cache }}
  DEBUG: ${{ inputs.debug == true || github.event.inputs.debug == 'true' || '' }}

jobs:
  docker_build:
    name: Docker Build -> AWS ECR
    runs-on: ubuntu-latest
    # better done in the calling workflow to prevent manual docker builds on the wrong branches
    #if: github.ref_name == 'master' || github.ref_name == 'main' || contains(github.ref_name, 'docker')
    steps:
      - name: Environment
        run: env | sort

      - uses: actions/checkout@v3
        with:
          submodules: 'true'  # requires Git 2.18+ to be installed first

      - name: Git Checkout Dockerfile repo
        if: ${{ inputs.dockerfile-repo }}
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.dockerfile-repo }}
          ref: ${{ inputs.dockerfile-ref }}
          submodules: 'true'  # requires Git 2.18+ to be installed first

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      #- name: Login to AWS ECR
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ${{ env.AWS_ECR_REGISTRY }}
      #    username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to AWS ECR
        id: aws-ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Login to GHCR
        if: ${{ inputs.max-cache }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # not needed when using ecr login output
      #- name: Generate environment variable AWS_ACCOUNT_ID
      #  run: |
      #    #AWS_ACCOUNT_ID="$(aws sts get-caller-identity | jq -r .Account)"
      #    #echo "AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID" >> "$GITHUB_ENV"
      #    echo "AWS_ACCOUNT_ID=${{ steps.configure-aws-credentials.outputs.aws-account-id }}" >> "$GITHUB_ENV"

      #- name: Generate environment variable AWS_ECR_REGISTRY
      #  #run: echo "AWS_ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com" >> "$GITHUB_ENV"
      #  env:
      #    REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
      #  run: echo "AWS_ECR_REGISTRY=$REGISTRY" >> "$GITHUB_ENV"

      - name: Generate environment variable DOCKER_IMAGE
        env:
          REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
        run: echo "DOCKER_IMAGE=$REGISTRY/$AWS_ECR_REPO" >> "$GITHUB_ENV"

      - uses: HariSekhon/GitHub-Actions/generate-docker-tags@master

      - name: Generate environment variable DOCKER_IMAGE_CACHE
        if: ${{ inputs.max-cache }}
        #run: echo "DOCKER_IMAGE_CACHE=$AWS_ECR_REGISTRY/$APP-cache" >> $GITHUB_ENV  # doesn't work, ECR simply doesn't support it
        env:
          REPO: ${{ github.repository }}
        run: echo "DOCKER_IMAGE_CACHE=ghcr.io/$REPO" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # XXX: Normal build, use inline cache when max-cache input is not set to 'true' - fine for most purposes except for multi-stage builds
      - name: Docker Build & Push
        if: ${{ ! inputs.max-cache }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          cache-from: |
            type=registry,ref=${{env.DOCKER_IMAGE}}:latest
            type=registry,ref=${{env.DOCKER_IMAGE}}:${{env.BRANCH_TAG}}
            type=registry,ref=${{env.DOCKER_IMAGE}}:${{github.sha}}
          cache-to: type=inline
          tags: |
            ${{env.DOCKER_IMAGE}}:latest
            ${{env.DOCKER_IMAGE}}:${{env.BRANCH_TAG}}
            ${{env.DOCKER_IMAGE}}:${{github.sha}}
            ${{env.DOCKER_IMAGE}}:${{env.EPOCH}}
            ${{env.DOCKER_IMAGE}}:${{env.DATESTAMP}}
            ${{env.DOCKER_IMAGE}}:${{env.TIMESTAMP}}

      # XXX: Max Cache build with separate GHCR buildcache since ECR doesn't support it - for multi-stage builds
      #
      # call like so:
      #
      #   jobs:
      #     docker_build:
      #       uses: HariSekhon/GitHub-Actions/.github/workflows/docker_build_aws_ecr.yaml@master
      #       with:
      #         max-cache: true
      #         ...
      #
      - name: Docker Build & Push with external GHCR registry max cache
        if: ${{ inputs.max-cache }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
          cache-from: |
            type=registry,ref=${{env.DOCKER_IMAGE_CACHE}}:${{env.BUILDCACHE}}
            type=registry,ref=${{env.DOCKER_IMAGE}}:latest
            type=registry,ref=${{env.DOCKER_IMAGE}}:${{env.BRANCH_TAG}}
            type=registry,ref=${{env.DOCKER_IMAGE}}:${{github.sha}}
          cache-to: type=registry,ref=${{env.DOCKER_IMAGE_CACHE}}:${{env.BUILDCACHE}},mode=max  # XXX: fails to push to ECR which doesn't support external registry cache export, so set to GHCR for cache instead
          tags: |
            ${{env.DOCKER_IMAGE}}:latest
            ${{env.DOCKER_IMAGE}}:${{env.BRANCH_TAG}}
            ${{env.DOCKER_IMAGE}}:${{github.sha}}
            ${{env.DOCKER_IMAGE}}:${{env.EPOCH}}
            ${{env.DOCKER_IMAGE}}:${{env.DATESTAMP}}
            ${{env.DOCKER_IMAGE}}:${{env.TIMESTAMP}}
