#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2023-05-31 01:49:54 +0100 (Wed, 31 May 2023)
#
#  https://github.com/HariSekhon/Templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                        R e d h a t   K i c k s t a r t
# ============================================================================ #

---
name: Redhat Kickstart

on:
  workflow_call:
    inputs:
      files:
        description: The Redhat Kickstart file paths to validate, separated by spaces
        type: string
        required: false
        default: anaconda-ks.cfg

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  kickstart:
    name: Kickstart
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - uses: actions/checkout@v3
        #name: Git Checkout  # better to show the action@version

      - name: Install pykickstart
        run: dnf install pykickstart -y

      - name: Validate Kickstart
        run: |
          for file in ${{ inputs.files }}; do
            echo "Validating $file"
            echo
            ksvalidator "$file"
            echo
          done
