#
#  Author: Hari Sekhon
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: Perl

on:
  workflow_call:
    inputs:
      version:
        description: Perl version tag for the docker image
        type: string
        required: true
      debug:
        type: string
        required: false
        default: false

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBIAN_FRONTEND: noninteractive
  DEBUG: ${{ inputs.debug != 'false' || github.event.inputs.debug != 'false' || '' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: perl:${{ inputs.version }}
    steps:
      - name: Environment
        run: env | sort

      - name: Install Git & Make
        run: apt-get update && apt-get install -y git make

      - name: Git version
        run: git --version

      - name: Git Checkout
        #uses: actions/checkout@v2
        #with:
        #  submodules: recursive  # requires Git 2.18+ to be installed first
        run: git clone "https://${{github.token}}@github.com/$GITHUB_REPOSITORY" "$GITHUB_WORKSPACE"

      - name: Init
        run: |
          if grep -q '^init:' Makefile; then
            make init
          fi

      - name: Build
        run: |
          if grep -q '^ci:' Makefile; then
            make ci
          elif grep -q '^build:' Makefile; then
            make build
          else
            make
          fi

      - name: Fatpacks
        run: |
          if grep -q '^fatpacks:' Makefile; then
            make fatpacks
          fi

      - name: Test
        run: |
          if grep -q '^test:' Makefile; then
            make test
          fi
